/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorConsumer;
import org.nazymko.th.parser.autodao.tables.ConnectorRules;
import org.nazymko.th.parser.autodao.tables.ConnectorSyncPageLog;
import org.nazymko.th.parser.autodao.tables.ConnectorsSendHeaders;
import org.nazymko.th.parser.autodao.tables.TaskRun;
import org.nazymko.th.parser.autodao.tables.TaskSchedule;
import org.nazymko.th.parser.autodao.tables.ThAttributeData;
import org.nazymko.th.parser.autodao.tables.ThConfig;
import org.nazymko.th.parser.autodao.tables.ThPage;
import org.nazymko.th.parser.autodao.tables.ThRule;
import org.nazymko.th.parser.autodao.tables.ThSite;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Thehomeland extends SchemaImpl {

	private static final long serialVersionUID = -813855839;

	/**
	 * The reference instance of <code>thehomeland</code>
	 */
	public static final Thehomeland THEHOMELAND = new Thehomeland();

	/**
	 * No further instances allowed
	 */
	private Thehomeland() {
		super("thehomeland");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS,
			ConnectorConsumer.CONNECTOR_CONSUMER,
			ConnectorRules.CONNECTOR_RULES,
			ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG,
			TaskRun.TASK_RUN,
			TaskSchedule.TASK_SCHEDULE,
			ThAttributeData.TH_ATTRIBUTE_DATA,
			ThConfig.TH_CONFIG,
			ThPage.TH_PAGE,
			ThRule.TH_RULE,
			ThSite.TH_SITE);
	}
}
