/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "connector_rules", schema = "thehomeland")
public class ConnectorRules implements Serializable {

	private static final long serialVersionUID = -2054073225;

	private Integer id;
	private String  rule;
	private Integer consumerId;
	private Integer siteId;

	public ConnectorRules() {}

	public ConnectorRules(ConnectorRules value) {
		this.id = value.id;
		this.rule = value.rule;
		this.consumerId = value.consumerId;
		this.siteId = value.siteId;
	}

	public ConnectorRules(
		Integer id,
		String  rule,
		Integer consumerId,
		Integer siteId
	) {
		this.id = id;
		this.rule = rule;
		this.consumerId = consumerId;
		this.siteId = siteId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rule", length = 65535)
	@Size(max = 65535)
	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	@Column(name = "consumer_id", precision = 10)
	public Integer getConsumerId() {
		return this.consumerId;
	}

	public void setConsumerId(Integer consumerId) {
		this.consumerId = consumerId;
	}

	@Column(name = "site_id", precision = 10)
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ConnectorRules (");

		sb.append(id);
		sb.append(", ").append(rule);
		sb.append(", ").append(consumerId);
		sb.append(", ").append(siteId);

		sb.append(")");
		return sb.toString();
	}
}
