/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "connector_consumer", schema = "thehomeland")
public class ConnectorConsumer implements Serializable {

	private static final long serialVersionUID = 1374687357;

	private Integer   id;
	private String    domain;
	private Timestamp time;

	public ConnectorConsumer() {}

	public ConnectorConsumer(ConnectorConsumer value) {
		this.id = value.id;
		this.domain = value.domain;
		this.time = value.time;
	}

	public ConnectorConsumer(
		Integer   id,
		String    domain,
		Timestamp time
	) {
		this.id = id;
		this.domain = domain;
		this.time = time;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "domain", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "time", nullable = false)
	@NotNull
	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ConnectorConsumer (");

		sb.append(id);
		sb.append(", ").append(domain);
		sb.append(", ").append(time);

		sb.append(")");
		return sb.toString();
	}
}
