/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "connector_sync_page_log", schema = "thehomeland")
public class ConnectorSyncPageLog implements Serializable {

	private static final long serialVersionUID = -1564492515;

	private Integer   id;
	private Integer   pageId;
	private String    consumer;
	private Timestamp time;
	private String    responseText;
	private Integer   responseCode;

	public ConnectorSyncPageLog() {}

	public ConnectorSyncPageLog(ConnectorSyncPageLog value) {
		this.id = value.id;
		this.pageId = value.pageId;
		this.consumer = value.consumer;
		this.time = value.time;
		this.responseText = value.responseText;
		this.responseCode = value.responseCode;
	}

	public ConnectorSyncPageLog(
		Integer   id,
		Integer   pageId,
		String    consumer,
		Timestamp time,
		String    responseText,
		Integer   responseCode
	) {
		this.id = id;
		this.pageId = pageId;
		this.consumer = consumer;
		this.time = time;
		this.responseText = responseText;
		this.responseCode = responseCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "page_id", nullable = false, precision = 10)
	@NotNull
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "consumer", nullable = false, length = 128)
	@NotNull
	@Size(max = 128)
	public String getConsumer() {
		return this.consumer;
	}

	public void setConsumer(String consumer) {
		this.consumer = consumer;
	}

	@Column(name = "time", nullable = false)
	@NotNull
	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	@Column(name = "response_text")
	public String getResponseText() {
		return this.responseText;
	}

	public void setResponseText(String responseText) {
		this.responseText = responseText;
	}

	@Column(name = "response_code", precision = 10)
	public Integer getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(Integer responseCode) {
		this.responseCode = responseCode;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ConnectorSyncPageLog (");

		sb.append(id);
		sb.append(", ").append(pageId);
		sb.append(", ").append(consumer);
		sb.append(", ").append(time);
		sb.append(", ").append(responseText);
		sb.append(", ").append(responseCode);

		sb.append(")");
		return sb.toString();
	}
}
