/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "th_attribute_data", schema = "thehomeland")
public class ThAttributeData implements Serializable {

	private static final long serialVersionUID = 275528163;

	private Integer id;
	private Integer siteId;
	private Integer pageId;
	private String  attributeName;
	private String  attributeValue;
	private Integer attributeIndex;
	private String  attributeType;
	private String  attributeFormat;
	private Integer ruleId;

	public ThAttributeData() {}

	public ThAttributeData(ThAttributeData value) {
		this.id = value.id;
		this.siteId = value.siteId;
		this.pageId = value.pageId;
		this.attributeName = value.attributeName;
		this.attributeValue = value.attributeValue;
		this.attributeIndex = value.attributeIndex;
		this.attributeType = value.attributeType;
		this.attributeFormat = value.attributeFormat;
		this.ruleId = value.ruleId;
	}

	public ThAttributeData(
		Integer id,
		Integer siteId,
		Integer pageId,
		String  attributeName,
		String  attributeValue,
		Integer attributeIndex,
		String  attributeType,
		String  attributeFormat,
		Integer ruleId
	) {
		this.id = id;
		this.siteId = siteId;
		this.pageId = pageId;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
		this.attributeIndex = attributeIndex;
		this.attributeType = attributeType;
		this.attributeFormat = attributeFormat;
		this.ruleId = ruleId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", precision = 10)
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Column(name = "page_id", precision = 10)
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Column(name = "attribute_name", nullable = false, length = 64)
	@NotNull
	@Size(max = 64)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "attribute_value")
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Column(name = "attribute_index", precision = 10)
	public Integer getAttributeIndex() {
		return this.attributeIndex;
	}

	public void setAttributeIndex(Integer attributeIndex) {
		this.attributeIndex = attributeIndex;
	}

	@Column(name = "attribute_type", length = 32)
	@Size(max = 32)
	public String getAttributeType() {
		return this.attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	@Column(name = "attribute_format", length = 256)
	@Size(max = 256)
	public String getAttributeFormat() {
		return this.attributeFormat;
	}

	public void setAttributeFormat(String attributeFormat) {
		this.attributeFormat = attributeFormat;
	}

	@Column(name = "rule_id", precision = 10)
	public Integer getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ThAttributeData (");

		sb.append(id);
		sb.append(", ").append(siteId);
		sb.append(", ").append(pageId);
		sb.append(", ").append(attributeName);
		sb.append(", ").append(attributeValue);
		sb.append(", ").append(attributeIndex);
		sb.append(", ").append(attributeType);
		sb.append(", ").append(attributeFormat);
		sb.append(", ").append(ruleId);

		sb.append(")");
		return sb.toString();
	}
}
