/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "th_config", schema = "thehomeland")
public class ThConfig implements Serializable {

	private static final long serialVersionUID = 1845308342;

	private Integer id;
	private String  name;
	private String  value;

	public ThConfig() {}

	public ThConfig(ThConfig value) {
		this.id = value.id;
		this.name = value.name;
		this.value = value.value;
	}

	public ThConfig(
		Integer id,
		String  name,
		String  value
	) {
		this.id = id;
		this.name = name;
		this.value = value;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 128)
	@NotNull
	@Size(max = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false)
	@NotNull
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ThConfig (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(value);

		sb.append(")");
		return sb.toString();
	}
}
