/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import utils.support.rule.RuleStatus;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "th_rule", schema = "thehomeland")
public class ThRule implements Serializable {

    private static final long serialVersionUID = -1873603415;

    private Integer id;
    private String site;
    private String rule;
    private Integer version;
    private RuleStatus status;
    private String authority;

    public ThRule() {
    }

    public ThRule(ThRule value) {
        this.id = value.id;
        this.site = value.site;
        this.rule = value.rule;
        this.version = value.version;
        this.status = value.status;
        this.authority = value.authority;
    }

    public ThRule(
            Integer id,
            String site,
            String rule,
            Integer version,
            RuleStatus status,
            String authority
    ) {
        this.id = id;
        this.site = site;
        this.rule = rule;
        this.version = version;
        this.status = status;
        this.authority = authority;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "site", nullable = false, length = 256)
    @NotNull
    @Size(max = 256)
    public String getSite() {
        return this.site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    @Column(name = "rule", nullable = false)
    @NotNull
    public String getRule() {
        return this.rule;
    }

    public void setRule(String rule) {
        this.rule = rule;
    }

    @Column(name = "version", nullable = false, precision = 10)
    @NotNull
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "status", precision = 10)
    public RuleStatus getStatus() {
        return this.status;
    }

    public void setStatus(RuleStatus status) {
        this.status = status;
    }

    @Column(name = "authority", nullable = false)
    @NotNull
    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThRule (");

        sb.append(id);
        sb.append(", ").append(site);
        sb.append(", ").append(rule);
        sb.append(", ").append(version);
        sb.append(", ").append(status);
        sb.append(", ").append(authority);

        sb.append(")");
        return sb.toString();
    }
}
