/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.pojos;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "th_site", schema = "thehomeland")
public class ThSite implements Serializable {

    private static final long serialVersionUID = -1886192114;

    private Integer id;
    private String url;
    private String name;

    public ThSite() {
    }

    public ThSite(ThSite value) {
        this.id = value.id;
        this.url = value.url;
        this.name = value.name;
    }

    public ThSite(
            Integer id,
            String url,
            String name
    ) {
        this.id = id;
        this.url = url;
        this.name = name;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, precision = 10)
    @NotNull
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "url", length = 256)
    @Size(max = 256)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "name", length = 128)
    @Size(max = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThSite (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
