/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorConsumer;
import org.nazymko.th.parser.autodao.tables.records.ConnectorConsumerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectorConsumerDao extends DAOImpl<ConnectorConsumerRecord, org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer, Integer> {

	/**
	 * Create a new ConnectorConsumerDao without any configuration
	 */
	public ConnectorConsumerDao() {
		super(ConnectorConsumer.CONNECTOR_CONSUMER, org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer.class);
	}

	/**
	 * Create a new ConnectorConsumerDao with an attached configuration
	 */
	public ConnectorConsumerDao(Configuration configuration) {
		super(ConnectorConsumer.CONNECTOR_CONSUMER, org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer> fetchById(Integer... values) {
		return fetch(ConnectorConsumer.CONNECTOR_CONSUMER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer fetchOneById(Integer value) {
		return fetchOne(ConnectorConsumer.CONNECTOR_CONSUMER.ID, value);
	}

	/**
	 * Fetch records that have <code>domain IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer> fetchByDomain(String... values) {
		return fetch(ConnectorConsumer.CONNECTOR_CONSUMER.DOMAIN, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorConsumer> fetchByTime(Timestamp... values) {
		return fetch(ConnectorConsumer.CONNECTOR_CONSUMER.TIME, values);
	}
}
