/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorRules;
import org.nazymko.th.parser.autodao.tables.records.ConnectorRulesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectorRulesDao extends DAOImpl<ConnectorRulesRecord, org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules, Integer> {

	/**
	 * Create a new ConnectorRulesDao without any configuration
	 */
	public ConnectorRulesDao() {
		super(ConnectorRules.CONNECTOR_RULES, org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules.class);
	}

	/**
	 * Create a new ConnectorRulesDao with an attached configuration
	 */
	public ConnectorRulesDao(Configuration configuration) {
		super(ConnectorRules.CONNECTOR_RULES, org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules> fetchById(Integer... values) {
		return fetch(ConnectorRules.CONNECTOR_RULES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules fetchOneById(Integer value) {
		return fetchOne(ConnectorRules.CONNECTOR_RULES.ID, value);
	}

	/**
	 * Fetch records that have <code>rule IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules> fetchByRule(String... values) {
		return fetch(ConnectorRules.CONNECTOR_RULES.RULE, values);
	}

	/**
	 * Fetch records that have <code>consumer_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules> fetchByConsumerId(Integer... values) {
		return fetch(ConnectorRules.CONNECTOR_RULES.CONSUMER_ID, values);
	}

	/**
	 * Fetch records that have <code>site_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorRules> fetchBySiteId(Integer... values) {
		return fetch(ConnectorRules.CONNECTOR_RULES.SITE_ID, values);
	}
}
