/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorsSendHeaders;
import org.nazymko.th.parser.autodao.tables.records.ConnectorsSendHeadersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectorsSendHeadersDao extends DAOImpl<ConnectorsSendHeadersRecord, org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders, Integer> {

	/**
	 * Create a new ConnectorsSendHeadersDao without any configuration
	 */
	public ConnectorsSendHeadersDao() {
		super(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS, org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders.class);
	}

	/**
	 * Create a new ConnectorsSendHeadersDao with an attached configuration
	 */
	public ConnectorsSendHeadersDao(Configuration configuration) {
		super(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS, org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders> fetchById(Integer... values) {
		return fetch(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders fetchOneById(Integer value) {
		return fetchOne(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.ID, value);
	}

	/**
	 * Fetch records that have <code>header IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders> fetchByHeader(String... values) {
		return fetch(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.HEADER, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders> fetchByValue(String... values) {
		return fetch(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.VALUE, values);
	}

	/**
	 * Fetch records that have <code>consumer_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ConnectorsSendHeaders> fetchByConsumerId(Integer... values) {
		return fetch(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.CONSUMER_ID, values);
	}
}
