/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.TaskRun;
import org.nazymko.th.parser.autodao.tables.records.TaskRunRecord;

import utils.support.runtype.RunType;
import utils.support.task.TaskStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRunDao extends DAOImpl<TaskRunRecord, org.nazymko.th.parser.autodao.tables.pojos.TaskRun, Integer> {

	/**
	 * Create a new TaskRunDao without any configuration
	 */
	public TaskRunDao() {
		super(TaskRun.TASK_RUN, org.nazymko.th.parser.autodao.tables.pojos.TaskRun.class);
	}

	/**
	 * Create a new TaskRunDao with an attached configuration
	 */
	public TaskRunDao(Configuration configuration) {
		super(TaskRun.TASK_RUN, org.nazymko.th.parser.autodao.tables.pojos.TaskRun.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.TaskRun object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchById(Integer... values) {
		return fetch(TaskRun.TASK_RUN.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.th.parser.autodao.tables.pojos.TaskRun fetchOneById(Integer value) {
		return fetchOne(TaskRun.TASK_RUN.ID, value);
	}

	/**
	 * Fetch records that have <code>start_at IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByStartAt(Timestamp... values) {
		return fetch(TaskRun.TASK_RUN.START_AT, values);
	}

	/**
	 * Fetch records that have <code>schedule_source_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByScheduleSourceId(Integer... values) {
		return fetch(TaskRun.TASK_RUN.SCHEDULE_SOURCE_ID, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByStatus(TaskStatus... values) {
		return fetch(TaskRun.TASK_RUN.STATUS, values);
	}

	/**
	 * Fetch records that have <code>message IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByMessage(String... values) {
		return fetch(TaskRun.TASK_RUN.MESSAGE, values);
	}

	/**
	 * Fetch records that have <code>is_enabled IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByIsEnabled(Boolean... values) {
		return fetch(TaskRun.TASK_RUN.IS_ENABLED, values);
	}

	/**
	 * Fetch records that have <code>finish_at IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByFinishAt(Timestamp... values) {
		return fetch(TaskRun.TASK_RUN.FINISH_AT, values);
	}

	/**
	 * Fetch records that have <code>run_type IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchByRunType(RunType... values) {
		return fetch(TaskRun.TASK_RUN.RUN_TYPE, values);
	}

	/**
	 * Fetch records that have <code>site_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.TaskRun> fetchBySiteId(Integer... values) {
		return fetch(TaskRun.TASK_RUN.SITE_ID, values);
	}
}
