/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ThAttributeData;
import org.nazymko.th.parser.autodao.tables.records.ThAttributeDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThAttributeDataDao extends DAOImpl<ThAttributeDataRecord, org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData, Integer> {

	/**
	 * Create a new ThAttributeDataDao without any configuration
	 */
	public ThAttributeDataDao() {
		super(ThAttributeData.TH_ATTRIBUTE_DATA, org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData.class);
	}

	/**
	 * Create a new ThAttributeDataDao with an attached configuration
	 */
	public ThAttributeDataDao(Configuration configuration) {
		super(ThAttributeData.TH_ATTRIBUTE_DATA, org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchById(Integer... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData fetchOneById(Integer value) {
		return fetchOne(ThAttributeData.TH_ATTRIBUTE_DATA.ID, value);
	}

	/**
	 * Fetch records that have <code>site_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchBySiteId(Integer... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.SITE_ID, values);
	}

	/**
	 * Fetch records that have <code>page_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByPageId(Integer... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.PAGE_ID, values);
	}

	/**
	 * Fetch records that have <code>attribute_name IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByAttributeName(String... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ATTRIBUTE_NAME, values);
	}

	/**
	 * Fetch records that have <code>attribute_value IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByAttributeValue(String... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ATTRIBUTE_VALUE, values);
	}

	/**
	 * Fetch records that have <code>attribute_index IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByAttributeIndex(Integer... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ATTRIBUTE_INDEX, values);
	}

	/**
	 * Fetch records that have <code>attribute_type IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByAttributeType(String... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ATTRIBUTE_TYPE, values);
	}

	/**
	 * Fetch records that have <code>attribute_format IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByAttributeFormat(String... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.ATTRIBUTE_FORMAT, values);
	}

	/**
	 * Fetch records that have <code>rule_id IN (values)</code>
	 */
	public List<org.nazymko.th.parser.autodao.tables.pojos.ThAttributeData> fetchByRuleId(Integer... values) {
		return fetch(ThAttributeData.TH_ATTRIBUTE_DATA.RULE_ID, values);
	}
}
