/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ThPage;
import org.nazymko.th.parser.autodao.tables.records.ThPageRecord;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ThPageDao extends DAOImpl<ThPageRecord, org.nazymko.th.parser.autodao.tables.pojos.ThPage, Integer> {

    /**
     * Create a new ThPageDao without any configuration
     */
    public ThPageDao() {
        super(ThPage.TH_PAGE, org.nazymko.th.parser.autodao.tables.pojos.ThPage.class);
    }

    /**
     * Create a new ThPageDao with an attached configuration
     */
    public ThPageDao(Configuration configuration) {
        super(ThPage.TH_PAGE, org.nazymko.th.parser.autodao.tables.pojos.ThPage.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ThPage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchById(Integer... values) {
        return fetch(ThPage.TH_PAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.th.parser.autodao.tables.pojos.ThPage fetchOneById(Integer value) {
        return fetchOne(ThPage.TH_PAGE.ID, value);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByUrl(String... values) {
        return fetch(ThPage.TH_PAGE.URL, values);
    }

    /**
     * Fetch records that have <code>site_id IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchBySiteId(Integer... values) {
        return fetch(ThPage.TH_PAGE.SITE_ID, values);
    }

    /**
     * Fetch records that have <code>visited_at IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByVisitedAt(Timestamp... values) {
        return fetch(ThPage.TH_PAGE.VISITED_AT, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByType(String... values) {
        return fetch(ThPage.TH_PAGE.TYPE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByVersion(Integer... values) {
        return fetch(ThPage.TH_PAGE.VERSION, values);
    }

    /**
     * Fetch records that have <code>registered_at IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByRegisteredAt(Timestamp... values) {
        return fetch(ThPage.TH_PAGE.REGISTERED_AT, values);
    }

    /**
     * Fetch records that have <code>sourcePage IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchBySourcepage(Integer... values) {
        return fetch(ThPage.TH_PAGE.SOURCEPAGE, values);
    }

    /**
     * Fetch records that have <code>task_run_id IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchByTaskRunId(Integer... values) {
        return fetch(ThPage.TH_PAGE.TASK_RUN_ID, values);
    }

    /**
     * Fetch records that have <code>site_url IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThPage> fetchBySiteUrl(String... values) {
        return fetch(ThPage.TH_PAGE.SITE_URL, values);
    }
}
