/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ThRule;
import org.nazymko.th.parser.autodao.tables.records.ThRuleRecord;
import utils.support.rule.RuleStatus;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ThRuleDao extends DAOImpl<ThRuleRecord, org.nazymko.th.parser.autodao.tables.pojos.ThRule, Integer> {

    /**
     * Create a new ThRuleDao without any configuration
     */
    public ThRuleDao() {
        super(ThRule.TH_RULE, org.nazymko.th.parser.autodao.tables.pojos.ThRule.class);
    }

    /**
     * Create a new ThRuleDao with an attached configuration
     */
    public ThRuleDao(Configuration configuration) {
        super(ThRule.TH_RULE, org.nazymko.th.parser.autodao.tables.pojos.ThRule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ThRule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchById(Integer... values) {
        return fetch(ThRule.TH_RULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.th.parser.autodao.tables.pojos.ThRule fetchOneById(Integer value) {
        return fetchOne(ThRule.TH_RULE.ID, value);
    }

    /**
     * Fetch records that have <code>site IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchBySite(String... values) {
        return fetch(ThRule.TH_RULE.SITE, values);
    }

    /**
     * Fetch records that have <code>rule IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchByRule(String... values) {
        return fetch(ThRule.TH_RULE.RULE, values);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchByVersion(Integer... values) {
        return fetch(ThRule.TH_RULE.VERSION, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchByStatus(RuleStatus... values) {
        return fetch(ThRule.TH_RULE.STATUS, values);
    }

    /**
     * Fetch records that have <code>authority IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThRule> fetchByAuthority(String... values) {
        return fetch(ThRule.TH_RULE.AUTHORITY, values);
    }
}
