/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.daos;


import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.th.parser.autodao.tables.ThSite;
import org.nazymko.th.parser.autodao.tables.records.ThSiteRecord;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ThSiteDao extends DAOImpl<ThSiteRecord, org.nazymko.th.parser.autodao.tables.pojos.ThSite, Integer> {

    /**
     * Create a new ThSiteDao without any configuration
     */
    public ThSiteDao() {
        super(ThSite.TH_SITE, org.nazymko.th.parser.autodao.tables.pojos.ThSite.class);
    }

    /**
     * Create a new ThSiteDao with an attached configuration
     */
    public ThSiteDao(Configuration configuration) {
        super(ThSite.TH_SITE, org.nazymko.th.parser.autodao.tables.pojos.ThSite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.nazymko.th.parser.autodao.tables.pojos.ThSite object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThSite> fetchById(Integer... values) {
        return fetch(ThSite.TH_SITE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.nazymko.th.parser.autodao.tables.pojos.ThSite fetchOneById(Integer value) {
        return fetchOne(ThSite.TH_SITE.ID, value);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThSite> fetchByUrl(String... values) {
        return fetch(ThSite.TH_SITE.URL, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<org.nazymko.th.parser.autodao.tables.pojos.ThSite> fetchByName(String... values) {
        return fetch(ThSite.TH_SITE.NAME, values);
    }
}
