/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;
import org.nazymko.th.parser.autodao.tables.AttributeData;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributeDataRecord extends TableRecordImpl<AttributeDataRecord> implements Record8<Integer, Integer, String, String, Integer, String, String, Integer> {

	private static final long serialVersionUID = -477120006;

	/**
	 * Setter for <code>thehomeland.attribute_data.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.site_id</code>.
	 */
	public Integer getSiteId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.page_id</code>.
	 */
	public void setPageId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.page_id</code>.
	 */
	public Integer getPageId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.attribute_name</code>.
	 */
	public void setAttributeName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.attribute_name</code>.
	 */
	public String getAttributeName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.attribute_value</code>.
	 */
	public void setAttributeValue(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.attribute_value</code>.
	 */
	public String getAttributeValue() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.attribute_index</code>.
	 */
	public void setAttributeIndex(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.attribute_index</code>.
	 */
	public Integer getAttributeIndex() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.attribute_type</code>.
	 */
	public void setAttributeType(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.attribute_type</code>.
	 */
	public String getAttributeType() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.attribute_format</code>.
	 */
	public void setAttributeFormat(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.attribute_format</code>.
	 */
	public String getAttributeFormat() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>thehomeland.attribute_data.rule_id</code>.
	 */
	public void setRuleId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>thehomeland.attribute_data.rule_id</code>.
	 */
	public Integer getRuleId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, Integer, String, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, Integer, String, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AttributeData.ATTRIBUTE_DATA.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AttributeData.ATTRIBUTE_DATA.PAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AttributeData.ATTRIBUTE_DATA.ATTRIBUTE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AttributeData.ATTRIBUTE_DATA.ATTRIBUTE_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return AttributeData.ATTRIBUTE_DATA.ATTRIBUTE_INDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AttributeData.ATTRIBUTE_DATA.ATTRIBUTE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return AttributeData.ATTRIBUTE_DATA.ATTRIBUTE_FORMAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return AttributeData.ATTRIBUTE_DATA.RULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAttributeName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAttributeValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAttributeIndex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAttributeType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAttributeFormat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getRuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value1(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value2(Integer value) {
		setPageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value3(String value) {
		setAttributeName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value4(String value) {
		setAttributeValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value5(Integer value) {
		setAttributeIndex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value6(String value) {
		setAttributeType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value7(String value) {
		setAttributeFormat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord value8(Integer value) {
		setRuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeDataRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttributeDataRecord
	 */
	public AttributeDataRecord() {
		super(AttributeData.ATTRIBUTE_DATA);
	}

	/**
	 * Create a detached, initialised AttributeDataRecord
	 */
	public AttributeDataRecord(Integer siteId, Integer pageId, String attributeName, String attributeValue, Integer attributeIndex, String attributeType, String attributeFormat, Integer ruleId) {
		super(AttributeData.ATTRIBUTE_DATA);

		setValue(0, siteId);
		setValue(1, pageId);
		setValue(2, attributeName);
		setValue(3, attributeValue);
		setValue(4, attributeIndex);
		setValue(5, attributeType);
		setValue(6, attributeFormat);
		setValue(7, ruleId);
	}
}
