/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorSyncMainLog;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ConnectorSyncMainLogRecord extends UpdatableRecordImpl<ConnectorSyncMainLogRecord> implements Record6<Integer, String, Timestamp, Integer, Integer, Long> {

    private static final long serialVersionUID = -106854938;

    /**
     * Create a detached ConnectorSyncMainLogRecord
     */
    public ConnectorSyncMainLogRecord() {
        super(ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG);
    }

    /**
     * Create a detached, initialised ConnectorSyncMainLogRecord
     */
    public ConnectorSyncMainLogRecord(Integer id, String consumer, Timestamp syncDate, Integer countNew, Integer countTotal, Long latestPageId) {
        super(ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG);

        setValue(0, id);
        setValue(1, consumer);
        setValue(2, syncDate);
        setValue(3, countNew);
        setValue(4, countTotal);
        setValue(5, latestPageId);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.id</code>.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.id</code>.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.consumer</code>.
     */
    public String getConsumer() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.consumer</code>.
     */
    public void setConsumer(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.sync_date</code>.
     */
    public Timestamp getSyncDate() {
        return (Timestamp) getValue(2);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.sync_date</code>.
     */
    public void setSyncDate(Timestamp value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.count_new</code>.
     */
    public Integer getCountNew() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.count_new</code>.
     */
    public void setCountNew(Integer value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.count_total</code>.
     */
    public Integer getCountTotal() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.count_total</code>.
     */
    public void setCountTotal(Integer value) {
        setValue(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>thehomeland.connector_sync_main_log.latest_page_id</code>.
     */
    public Long getLatestPageId() {
        return (Long) getValue(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>thehomeland.connector_sync_main_log.latest_page_id</code>.
     */
    public void setLatestPageId(Long value) {
        setValue(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Integer, Integer, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Timestamp, Integer, Integer, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.CONSUMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.SYNC_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.COUNT_NEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.COUNT_TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ConnectorSyncMainLog.CONNECTOR_SYNC_MAIN_LOG.LATEST_PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getConsumer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getSyncDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCountNew();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCountTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getLatestPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value2(String value) {
        setConsumer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value3(Timestamp value) {
        setSyncDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value4(Integer value) {
        setCountNew(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value5(Integer value) {
        setCountTotal(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord value6(Long value) {
        setLatestPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncMainLogRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Integer value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
