/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorsSendHeaders;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "connectors_send_headers", schema = "thehomeland")
public class ConnectorsSendHeadersRecord extends UpdatableRecordImpl<ConnectorsSendHeadersRecord> implements Record4<Integer, String, String, Integer> {

	private static final long serialVersionUID = 558452166;

	/**
	 * Setter for <code>thehomeland.connectors_send_headers.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.connectors_send_headers.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.connectors_send_headers.header</code>.
	 */
	public void setHeader(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.connectors_send_headers.header</code>.
	 */
	@Column(name = "header", length = 128)
	@Size(max = 128)
	public String getHeader() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.connectors_send_headers.value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.connectors_send_headers.value</code>.
	 */
	@Column(name = "value", length = 1024)
	@Size(max = 1024)
	public String getValue() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.connectors_send_headers.consumer_id</code>.
	 */
	public void setConsumerId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.connectors_send_headers.consumer_id</code>.
	 */
	@Column(name = "consumer_id", precision = 10)
	public Integer getConsumerId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.HEADER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS.CONSUMER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getHeader();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getConsumerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorsSendHeadersRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorsSendHeadersRecord value2(String value) {
		setHeader(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorsSendHeadersRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorsSendHeadersRecord value4(Integer value) {
		setConsumerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorsSendHeadersRecord values(Integer value1, String value2, String value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConnectorsSendHeadersRecord
	 */
	public ConnectorsSendHeadersRecord() {
		super(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS);
	}

	/**
	 * Create a detached, initialised ConnectorsSendHeadersRecord
	 */
	public ConnectorsSendHeadersRecord(Integer id, String header, String value, Integer consumerId) {
		super(ConnectorsSendHeaders.CONNECTORS_SEND_HEADERS);

		setValue(0, id);
		setValue(1, header);
		setValue(2, value);
		setValue(3, consumerId);
	}
}
