/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorConsumer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "connector_consumer", schema = "thehomeland")
public class ConnectorConsumerRecord extends UpdatableRecordImpl<ConnectorConsumerRecord> implements Record3<Integer, String, Timestamp> {

	private static final long serialVersionUID = -1635766750;

	/**
	 * Setter for <code>thehomeland.connector_consumer.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.connector_consumer.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.connector_consumer.domain</code>.
	 */
	public void setDomain(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.connector_consumer.domain</code>.
	 */
	@Column(name = "domain", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getDomain() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.connector_consumer.time</code>.
	 */
	public void setTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.connector_consumer.time</code>.
	 */
	@Column(name = "time", nullable = false)
	@NotNull
	public Timestamp getTime() {
		return (Timestamp) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Timestamp> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Timestamp> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ConnectorConsumer.CONNECTOR_CONSUMER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ConnectorConsumer.CONNECTOR_CONSUMER.DOMAIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return ConnectorConsumer.CONNECTOR_CONSUMER.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDomain();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorConsumerRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorConsumerRecord value2(String value) {
		setDomain(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorConsumerRecord value3(Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorConsumerRecord values(Integer value1, String value2, Timestamp value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ConnectorConsumerRecord
	 */
	public ConnectorConsumerRecord() {
		super(ConnectorConsumer.CONNECTOR_CONSUMER);
	}

	/**
	 * Create a detached, initialised ConnectorConsumerRecord
	 */
	public ConnectorConsumerRecord(Integer id, String domain, Timestamp time) {
		super(ConnectorConsumer.CONNECTOR_CONSUMER);

		setValue(0, id);
		setValue(1, domain);
		setValue(2, time);
	}
}
