/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ConnectorSyncPageLog;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ConnectorSyncPageLogRecord extends UpdatableRecordImpl<ConnectorSyncPageLogRecord> implements Record4<Integer, String, Timestamp, Integer> {

    private static final long serialVersionUID = -220408956;

    /**
     * Create a detached ConnectorSyncPageLogRecord
     */
    public ConnectorSyncPageLogRecord() {
        super(ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG);
    }

    /**
     * Create a detached, initialised ConnectorSyncPageLogRecord
     */
    public ConnectorSyncPageLogRecord(Integer pageId, String consumer, Timestamp time, Integer id) {
        super(ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG);

        setValue(0, pageId);
        setValue(1, consumer);
        setValue(2, time);
        setValue(3, id);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_page_log.page_id</code>.
     */
    public Integer getPageId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_page_log.page_id</code>.
     */
    public void setPageId(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_page_log.consumer</code>.
     */
    public String getConsumer() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_page_log.consumer</code>.
     */
    public void setConsumer(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>thehomeland.connector_sync_page_log.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) getValue(2);
    }

    /**
     * Setter for <code>thehomeland.connector_sync_page_log.time</code>.
     */
    public void setTime(Timestamp value) {
        setValue(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>thehomeland.connector_sync_page_log.id</code>.
     */
    public Integer getId() {
        return (Integer) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>thehomeland.connector_sync_page_log.id</code>.
     */
    public void setId(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG.PAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG.CONSUMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ConnectorSyncPageLog.CONNECTOR_SYNC_PAGE_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getConsumer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncPageLogRecord value1(Integer value) {
        setPageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncPageLogRecord value2(String value) {
        setConsumer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncPageLogRecord value3(Timestamp value) {
        setTime(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncPageLogRecord value4(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConnectorSyncPageLogRecord values(Integer value1, String value2, Timestamp value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
