/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.Page;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageRecord extends UpdatableRecordImpl<PageRecord> implements Record8<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer> {

	private static final long serialVersionUID = -535452873;

	/**
	 * Setter for <code>thehomeland.page.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.page.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.page.url</code>.
	 */
	public void setUrl(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.page.url</code>.
	 */
	public String getUrl() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.page.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.page.site_id</code>.
	 */
	public Integer getSiteId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.page.visited_at</code>.
	 */
	public void setVisitedAt(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.page.visited_at</code>.
	 */
	public Timestamp getVisitedAt() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.page.type</code>.
	 */
	public void setType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.page.type</code>.
	 */
	public String getType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.page.version</code>.
	 */
	public void setVersion(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.page.version</code>.
	 */
	public Integer getVersion() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.page.registered_at</code>.
	 */
	public void setRegisteredAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.page.registered_at</code>.
	 */
	public Timestamp getRegisteredAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>thehomeland.page.sourcePage</code>.
	 */
	public void setSourcepage(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>thehomeland.page.sourcePage</code>.
	 */
	public Integer getSourcepage() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Page.PAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Page.PAGE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Page.PAGE.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Page.PAGE.VISITED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Page.PAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Page.PAGE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Page.PAGE.REGISTERED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Page.PAGE.SOURCEPAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getVisitedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getRegisteredAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getSourcepage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value2(String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value3(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value4(Timestamp value) {
		setVisitedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value5(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value6(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value7(Timestamp value) {
		setRegisteredAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord value8(Integer value) {
		setSourcepage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PageRecord values(Integer value1, String value2, Integer value3, Timestamp value4, String value5, Integer value6, Timestamp value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PageRecord
	 */
	public PageRecord() {
		super(Page.PAGE);
	}

	/**
	 * Create a detached, initialised PageRecord
	 */
	public PageRecord(Integer id, String url, Integer siteId, Timestamp visitedAt, String type, Integer version, Timestamp registeredAt, Integer sourcepage) {
		super(Page.PAGE);

		setValue(0, id);
		setValue(1, url);
		setValue(2, siteId);
		setValue(3, visitedAt);
		setValue(4, type);
		setValue(5, version);
		setValue(6, registeredAt);
		setValue(7, sourcepage);
	}
}
