/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.TaskRun;
import utils.support.runtype.RunType;
import utils.support.task.TaskStatus;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "task_run", schema = "thehomeland")
public class TaskRunRecord extends UpdatableRecordImpl<TaskRunRecord> implements Record9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> {

	private static final long serialVersionUID = -585062670;

	/**
	 * Create a detached TaskRunRecord
	 */
	public TaskRunRecord() {
		super(TaskRun.TASK_RUN);
	}

	/**
	 * Create a detached, initialised TaskRunRecord
	 */
	public TaskRunRecord(Integer id, Timestamp startAt, Integer scheduleSourceId, TaskStatus status, String message, Boolean isEnabled, Timestamp finishAt, RunType runType, Integer siteId) {
		super(TaskRun.TASK_RUN);

		setValue(0, id);
		setValue(1, startAt);
		setValue(2, scheduleSourceId);
		setValue(3, status);
		setValue(4, message);
		setValue(5, isEnabled);
		setValue(6, finishAt);
		setValue(7, runType);
		setValue(8, siteId);
	}

	/**
	 * Getter for <code>thehomeland.task_run.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.task_run.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.start_at</code>.
	 */
	@Column(name = "start_at", nullable = false)
	@NotNull
	public Timestamp getStartAt() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.task_run.start_at</code>.
	 */
	public void setStartAt(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.schedule_source_id</code>.
	 */
	@Column(name = "schedule_source_id", precision = 10)
	public Integer getScheduleSourceId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.task_run.schedule_source_id</code>.
	 */
	public void setScheduleSourceId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.status</code>.
	 */
	@Column(name = "status", precision = 10)
	public TaskStatus getStatus() {
		return (TaskStatus) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.task_run.status</code>.
	 */
	public void setStatus(TaskStatus value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.message</code>.
	 */
	@Column(name = "message")
	public String getMessage() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.task_run.message</code>.
	 */
	public void setMessage(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.is_enabled</code>.
	 */
	@Column(name = "is_enabled")
	public Boolean getIsEnabled() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.task_run.is_enabled</code>.
	 */
	public void setIsEnabled(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.finish_at</code>.
	 */
	@Column(name = "finish_at")
	public Timestamp getFinishAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>thehomeland.task_run.finish_at</code>.
	 */
	public void setFinishAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.task_run.run_type</code>.
	 */
	@Column(name = "run_type", nullable = false, precision = 10)
	@NotNull
	public RunType getRunType() {
		return (RunType) getValue(7);
	}

	/**
	 * Setter for <code>thehomeland.task_run.run_type</code>.
	 */
	public void setRunType(RunType value) {
		setValue(7, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehomeland.task_run.site_id</code>.
	 */
	@Column(name = "site_id", nullable = false, precision = 10)
	@NotNull
	public Integer getSiteId() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehomeland.task_run.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(8, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TaskRun.TASK_RUN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return TaskRun.TASK_RUN.START_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TaskRun.TASK_RUN.SCHEDULE_SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<TaskStatus> field4() {
		return TaskRun.TASK_RUN.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TaskRun.TASK_RUN.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TaskRun.TASK_RUN.IS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return TaskRun.TASK_RUN.FINISH_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<RunType> field8() {
		return TaskRun.TASK_RUN.RUN_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return TaskRun.TASK_RUN.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getStartAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getScheduleSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskStatus value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getFinishAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RunType value8() {
		return getRunType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value2(Timestamp value) {
		setStartAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value3(Integer value) {
		setScheduleSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value4(TaskStatus value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value5(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value6(Boolean value) {
		setIsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value7(Timestamp value) {
		setFinishAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value8(RunType value) {
		setRunType(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord value9(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRunRecord values(Integer value1, Timestamp value2, Integer value3, TaskStatus value4, String value5, Boolean value6, Timestamp value7, RunType value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}
}
