/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ThPage;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.2"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ThPageRecord extends UpdatableRecordImpl<ThPageRecord> implements Record10<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer, Integer, String> {

	private static final long serialVersionUID = -1855402505;

	/**
	 * Create a detached ThPageRecord
	 */
	public ThPageRecord() {
		super(ThPage.TH_PAGE);
	}

	/**
	 * Create a detached, initialised ThPageRecord
	 */
	public ThPageRecord(Integer id, String url, Integer siteId, Timestamp visitedAt, String type, Integer version, Timestamp registeredAt, Integer sourcepage, Integer taskRunId, String siteUrl) {
		super(ThPage.TH_PAGE);

		setValue(0, id);
		setValue(1, url);
		setValue(2, siteId);
		setValue(3, visitedAt);
		setValue(4, type);
		setValue(5, version);
		setValue(6, registeredAt);
		setValue(7, sourcepage);
		setValue(8, taskRunId);
		setValue(9, siteUrl);
	}

	/**
	 * Getter for <code>thehomeland.th_page.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.th_page.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.url</code>.
	 */
	public String getUrl() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.th_page.url</code>.
	 */
	public void setUrl(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.site_id</code>.
	 */
	public Integer getSiteId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.th_page.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.visited_at</code>.
	 */
	public Timestamp getVisitedAt() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.th_page.visited_at</code>.
	 */
	public void setVisitedAt(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.type</code>.
	 */
	public String getType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.th_page.type</code>.
	 */
	public void setType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.version</code>.
	 */
	public Integer getVersion() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.th_page.version</code>.
	 */
	public void setVersion(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.registered_at</code>.
	 */
	public Timestamp getRegisteredAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>thehomeland.th_page.registered_at</code>.
	 */
	public void setRegisteredAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.sourcePage</code>.
	 */
	public Integer getSourcepage() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>thehomeland.th_page.sourcePage</code>.
	 */
	public void setSourcepage(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>thehomeland.th_page.task_run_id</code>.
	 */
	public Integer getTaskRunId() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>thehomeland.th_page.task_run_id</code>.
	 */
	public void setTaskRunId(Integer value) {
		setValue(8, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehomeland.th_page.site_url</code>.
	 */
	public String getSiteUrl() {
		return (String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehomeland.th_page.site_url</code>.
	 */
	public void setSiteUrl(String value) {
		setValue(9, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer, Integer, String> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, String, Integer, Timestamp, String, Integer, Timestamp, Integer, Integer, String> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ThPage.TH_PAGE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ThPage.TH_PAGE.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return ThPage.TH_PAGE.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return ThPage.TH_PAGE.VISITED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return ThPage.TH_PAGE.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return ThPage.TH_PAGE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return ThPage.TH_PAGE.REGISTERED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return ThPage.TH_PAGE.SOURCEPAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return ThPage.TH_PAGE.TASK_RUN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return ThPage.TH_PAGE.SITE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getVisitedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getRegisteredAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getSourcepage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getTaskRunId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSiteUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value2(String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value3(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value4(Timestamp value) {
		setVisitedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value5(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value6(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value7(Timestamp value) {
		setRegisteredAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value8(Integer value) {
		setSourcepage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value9(Integer value) {
		setTaskRunId(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord value10(String value) {
		setSiteUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPageRecord values(Integer value1, String value2, Integer value3, Timestamp value4, String value5, Integer value6, Timestamp value7, Integer value8, Integer value9, String value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}
}
