/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ThRule;
import utils.support.rule.RuleStatus;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.2"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "th_rule", schema = "thehomeland")
public class ThRuleRecord extends UpdatableRecordImpl<ThRuleRecord> implements Record6<Integer, String, String, Integer, RuleStatus, String> {

	private static final long serialVersionUID = 661460538;

	/**
	 * Create a detached ThRuleRecord
	 */
	public ThRuleRecord() {
		super(ThRule.TH_RULE);
	}

	/**
	 * Create a detached, initialised ThRuleRecord
	 */
	public ThRuleRecord(Integer id, String site, String rule, Integer version, RuleStatus status, String authority) {
		super(ThRule.TH_RULE);

		setValue(0, id);
		setValue(1, site);
		setValue(2, rule);
		setValue(3, version);
		setValue(4, status);
		setValue(5, authority);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.site</code>.
	 */
	@Column(name = "site", nullable = false, length = 256)
	@NotNull
	@Size(max = 256)
	public String getSite() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.site</code>.
	 */
	public void setSite(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.rule</code>.
	 */
	@Column(name = "rule", nullable = false)
	@NotNull
	public String getRule() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.rule</code>.
	 */
	public void setRule(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.version</code>.
	 */
	@Column(name = "version", nullable = false, precision = 10)
	@NotNull
	public Integer getVersion() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.version</code>.
	 */
	public void setVersion(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.status</code>.
	 */
	@Column(name = "status", precision = 10)
	public RuleStatus getStatus() {
		return (RuleStatus) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.status</code>.
	 */
	public void setStatus(RuleStatus value) {
		setValue(4, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehomeland.th_rule.authority</code>.
	 */
	@Column(name = "authority", nullable = false)
	@NotNull
	public String getAuthority() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehomeland.th_rule.authority</code>.
	 */
	public void setAuthority(String value) {
		setValue(5, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Integer, RuleStatus, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Integer, RuleStatus, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ThRule.TH_RULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ThRule.TH_RULE.SITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return ThRule.TH_RULE.RULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return ThRule.TH_RULE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<RuleStatus> field5() {
		return ThRule.TH_RULE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return ThRule.TH_RULE.AUTHORITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getRule();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RuleStatus value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAuthority();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value2(String value) {
		setSite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value3(String value) {
		setRule(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value4(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value5(RuleStatus value) {
		setStatus(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value6(String value) {
		setAuthority(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord values(Integer value1, String value2, String value3, Integer value4, RuleStatus value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}
}
