/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.ThRule;
import utils.support.rule.RuleStatus;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.2"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ThRuleRecord extends UpdatableRecordImpl<ThRuleRecord> implements Record6<String, String, Integer, Integer, RuleStatus, String> {

	private static final long serialVersionUID = 928386173;

	/**
	 * Create a detached ThRuleRecord
	 */
	public ThRuleRecord() {
		super(ThRule.TH_RULE);
	}

	/**
	 * Create a detached, initialised ThRuleRecord
	 */
	public ThRuleRecord(String site, String rule, Integer version, Integer id, RuleStatus status, String authority) {
		super(ThRule.TH_RULE);

		setValue(0, site);
		setValue(1, rule);
		setValue(2, version);
		setValue(3, id);
		setValue(4, status);
		setValue(5, authority);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.site</code>.
	 */
	public String getSite() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.site</code>.
	 */
	public void setSite(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.rule</code>.
	 */
	public String getRule() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.rule</code>.
	 */
	public void setRule(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.version</code>.
	 */
	public Integer getVersion() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.version</code>.
	 */
	public void setVersion(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.id</code>.
	 */
	public void setId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.th_rule.status</code>.
	 */
	public RuleStatus getStatus() {
		return (RuleStatus) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.th_rule.status</code>.
	 */
	public void setStatus(RuleStatus value) {
		setValue(4, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehomeland.th_rule.authority</code>.
	 */
	public String getAuthority() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehomeland.th_rule.authority</code>.
	 */
	public void setAuthority(String value) {
		setValue(5, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, Integer, RuleStatus, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, String, Integer, Integer, RuleStatus, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return ThRule.TH_RULE.SITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ThRule.TH_RULE.RULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return ThRule.TH_RULE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return ThRule.TH_RULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<RuleStatus> field5() {
		return ThRule.TH_RULE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return ThRule.TH_RULE.AUTHORITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getRule();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RuleStatus value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAuthority();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value1(String value) {
		setSite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value2(String value) {
		setRule(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value3(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value4(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value5(RuleStatus value) {
		setStatus(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord value6(String value) {
		setAuthority(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThRuleRecord values(String value1, String value2, Integer value3, Integer value4, RuleStatus value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}
}
