/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.TSchedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TScheduleRecord extends UpdatableRecordImpl<TScheduleRecord> implements Record6<Integer, Integer, String, String, Timestamp, String> {

	private static final long serialVersionUID = 933054197;

	/**
	 * Setter for <code>thehomeland.t_schedule.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.siteId</code>.
	 */
	public void setSiteid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.siteId</code>.
	 */
	public Integer getSiteid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.start_page</code>.
	 */
	public void setStartPage(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.start_page</code>.
	 */
	public String getStartPage() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.page_type</code>.
	 */
	public void setPageType(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.page_type</code>.
	 */
	public String getPageType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.start_date</code>.
	 */
	public void setStartDate(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.start_date</code>.
	 */
	public Timestamp getStartDate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.period</code>.
	 */
	public void setPeriod(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.period</code>.
	 */
	public String getPeriod() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, String, String, Timestamp, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, String, String, Timestamp, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TSchedule.T_SCHEDULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TSchedule.T_SCHEDULE.SITEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TSchedule.T_SCHEDULE.START_PAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TSchedule.T_SCHEDULE.PAGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return TSchedule.T_SCHEDULE.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TSchedule.T_SCHEDULE.PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSiteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getStartPage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPageType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value2(Integer value) {
		setSiteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value3(String value) {
		setStartPage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value4(String value) {
		setPageType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value5(Timestamp value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value6(String value) {
		setPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TScheduleRecord
	 */
	public TScheduleRecord() {
		super(TSchedule.T_SCHEDULE);
	}

	/**
	 * Create a detached, initialised TScheduleRecord
	 */
	public TScheduleRecord(Integer id, Integer siteid, String startPage, String pageType, Timestamp startDate, String period) {
		super(TSchedule.T_SCHEDULE);

		setValue(0, id);
		setValue(1, siteid);
		setValue(2, startPage);
		setValue(3, pageType);
		setValue(4, startDate);
		setValue(5, period);
	}
}
