/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.TSchedule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TScheduleRecord extends UpdatableRecordImpl<TScheduleRecord> implements Record7<Integer, Integer, String, String, Timestamp, String, Boolean> {

	private static final long serialVersionUID = 153310180;

	/**
	 * Setter for <code>thehomeland.t_schedule.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.siteId</code>.
	 */
	public void setSiteid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.siteId</code>.
	 */
	public Integer getSiteid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.start_page</code>.
	 */
	public void setStartPage(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.start_page</code>.
	 */
	public String getStartPage() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.page_type</code>.
	 */
	public void setPageType(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.page_type</code>.
	 */
	public String getPageType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.start_at</code>.
	 */
	public void setStartAt(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.start_at</code>.
	 */
	public Timestamp getStartAt() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.cron</code>.
	 */
	public void setCron(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.cron</code>.
	 */
	public String getCron() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.t_schedule.is_enabled</code>.
	 */
	public void setIsEnabled(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.t_schedule.is_enabled</code>.
	 */
	public Boolean getIsEnabled() {
		return (Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, String, String, Timestamp, String, Boolean> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, String, String, Timestamp, String, Boolean> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TSchedule.T_SCHEDULE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TSchedule.T_SCHEDULE.SITEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TSchedule.T_SCHEDULE.START_PAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TSchedule.T_SCHEDULE.PAGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return TSchedule.T_SCHEDULE.START_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TSchedule.T_SCHEDULE.CRON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return TSchedule.T_SCHEDULE.IS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSiteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getStartPage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPageType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStartAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCron();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getIsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value2(Integer value) {
		setSiteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value3(String value) {
		setStartPage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value4(String value) {
		setPageType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value5(Timestamp value) {
		setStartAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value6(String value) {
		setCron(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord value7(Boolean value) {
		setIsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TScheduleRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5, String value6, Boolean value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TScheduleRecord
	 */
	public TScheduleRecord() {
		super(TSchedule.T_SCHEDULE);
	}

	/**
	 * Create a detached, initialised TScheduleRecord
	 */
	public TScheduleRecord(Integer id, Integer siteid, String startPage, String pageType, Timestamp startAt, String cron, Boolean isEnabled) {
		super(TSchedule.T_SCHEDULE);

		setValue(0, id);
		setValue(1, siteid);
		setValue(2, startPage);
		setValue(3, pageType);
		setValue(4, startAt);
		setValue(5, cron);
		setValue(6, isEnabled);
	}
}
