/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.TTask;

import utils.support.runtype.RunType;
import utils.support.task.TaskStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTaskRecord extends UpdatableRecordImpl<TTaskRecord> implements Record9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> {

	private static final long serialVersionUID = -1392734211;

	/**
	 * Setter for <code>thehomeland.t_task.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.t_task.start_at</code>.
	 */
	public void setStartAt(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.start_at</code>.
	 */
	public Timestamp getStartAt() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.t_task.schedule_source_id</code>.
	 */
	public void setScheduleSourceId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.schedule_source_id</code>.
	 */
	public Integer getScheduleSourceId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.t_task.status</code>.
	 */
	public void setStatus(TaskStatus value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.status</code>.
	 */
	public TaskStatus getStatus() {
		return (TaskStatus) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.t_task.message</code>.
	 */
	public void setMessage(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.message</code>.
	 */
	public String getMessage() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.t_task.is_enabled</code>.
	 */
	public void setIsEnabled(Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.is_enabled</code>.
	 */
	public Boolean getIsEnabled() {
		return (Boolean) getValue(5);
	}

	/**
	 * Setter for <code>thehomeland.t_task.finish_at</code>.
	 */
	public void setFinishAt(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.finish_at</code>.
	 */
	public Timestamp getFinishAt() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>thehomeland.t_task.run_type</code>.
	 */
	public void setRunType(RunType value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.run_type</code>.
	 */
	public RunType getRunType() {
		return (RunType) getValue(7);
	}

	/**
	 * Setter for <code>thehomeland.t_task.site_id</code>.
	 */
	public void setSiteId(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.site_id</code>.
	 */
	public Integer getSiteId() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, TaskStatus, String, Boolean, Timestamp, RunType, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TTask.T_TASK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return TTask.T_TASK.START_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return TTask.T_TASK.SCHEDULE_SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<TaskStatus> field4() {
		return TTask.T_TASK.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TTask.T_TASK.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field6() {
		return TTask.T_TASK.IS_ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return TTask.T_TASK.FINISH_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<RunType> field8() {
		return TTask.T_TASK.RUN_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return TTask.T_TASK.SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getStartAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getScheduleSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskStatus value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value6() {
		return getIsEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getFinishAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RunType value8() {
		return getRunType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value2(Timestamp value) {
		setStartAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value3(Integer value) {
		setScheduleSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value4(TaskStatus value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value5(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value6(Boolean value) {
		setIsEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value7(Timestamp value) {
		setFinishAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value8(RunType value) {
		setRunType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value9(Integer value) {
		setSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord values(Integer value1, Timestamp value2, Integer value3, TaskStatus value4, String value5, Boolean value6, Timestamp value7, RunType value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TTaskRecord
	 */
	public TTaskRecord() {
		super(TTask.T_TASK);
	}

	/**
	 * Create a detached, initialised TTaskRecord
	 */
	public TTaskRecord(Integer id, Timestamp startAt, Integer scheduleSourceId, TaskStatus status, String message, Boolean isEnabled, Timestamp finishAt, RunType runType, Integer siteId) {
		super(TTask.T_TASK);

		setValue(0, id);
		setValue(1, startAt);
		setValue(2, scheduleSourceId);
		setValue(3, status);
		setValue(4, message);
		setValue(5, isEnabled);
		setValue(6, finishAt);
		setValue(7, runType);
		setValue(8, siteId);
	}
}
