/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.th.parser.autodao.tables.TTask;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTaskRecord extends UpdatableRecordImpl<TTaskRecord> implements Record6<Integer, Integer, Timestamp, Timestamp, Integer, String> {

	private static final long serialVersionUID = 705730362;

	/**
	 * Setter for <code>thehomeland.t_task.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>thehomeland.t_task.schedule_source_id</code>.
	 */
	public void setScheduleSourceId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.schedule_source_id</code>.
	 */
	public Integer getScheduleSourceId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>thehomeland.t_task.start_at</code>.
	 */
	public void setStartAt(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.start_at</code>.
	 */
	public Timestamp getStartAt() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>thehomeland.t_task.finish_at</code>.
	 */
	public void setFinishAt(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.finish_at</code>.
	 */
	public Timestamp getFinishAt() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>thehomeland.t_task.status</code>.
	 */
	public void setStatus(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.status</code>.
	 */
	public Integer getStatus() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>thehomeland.t_task.message</code>.
	 */
	public void setMessage(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>thehomeland.t_task.message</code>.
	 */
	public String getMessage() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Timestamp, Timestamp, Integer, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Timestamp, Timestamp, Integer, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TTask.T_TASK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TTask.T_TASK.SCHEDULE_SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return TTask.T_TASK.START_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return TTask.T_TASK.FINISH_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return TTask.T_TASK.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TTask.T_TASK.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getScheduleSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getStartAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getFinishAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value2(Integer value) {
		setScheduleSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value3(Timestamp value) {
		setStartAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value4(Timestamp value) {
		setFinishAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value5(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord value6(String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTaskRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4, Integer value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TTaskRecord
	 */
	public TTaskRecord() {
		super(TTask.T_TASK);
	}

	/**
	 * Create a detached, initialised TTaskRecord
	 */
	public TTaskRecord(Integer id, Integer scheduleSourceId, Timestamp startAt, Timestamp finishAt, Integer status, String message) {
		super(TTask.T_TASK);

		setValue(0, id);
		setValue(1, scheduleSourceId);
		setValue(2, startAt);
		setValue(3, finishAt);
		setValue(4, status);
		setValue(5, message);
	}
}
