/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.nazymko.th.parser.autodao.Keys;
import org.nazymko.th.parser.autodao.Thehomeland;
import org.nazymko.th.parser.autodao.tables.records.AttributeDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributeData extends TableImpl<AttributeDataRecord> {

	private static final long serialVersionUID = -589613425;

	/**
	 * The reference instance of <code>thehomeland.attribute_data</code>
	 */
	public static final AttributeData ATTRIBUTE_DATA = new AttributeData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AttributeDataRecord> getRecordType() {
		return AttributeDataRecord.class;
	}

	/**
	 * The column <code>thehomeland.attribute_data.site_id</code>.
	 */
	public final TableField<AttributeDataRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>thehomeland.attribute_data.page_id</code>.
	 */
	public final TableField<AttributeDataRecord, Integer> PAGE_ID = createField("page_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>thehomeland.attribute_data.attribute_name</code>.
	 */
	public final TableField<AttributeDataRecord, String> ATTRIBUTE_NAME = createField("attribute_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>thehomeland.attribute_data.attribute_value</code>.
	 */
	public final TableField<AttributeDataRecord, String> ATTRIBUTE_VALUE = createField("attribute_value", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>thehomeland.attribute_data.attribute_index</code>.
	 */
	public final TableField<AttributeDataRecord, Integer> ATTRIBUTE_INDEX = createField("attribute_index", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>thehomeland.attribute_data.attribute_type</code>.
	 */
	public final TableField<AttributeDataRecord, String> ATTRIBUTE_TYPE = createField("attribute_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>thehomeland.attribute_data.attribute_format</code>.
	 */
	public final TableField<AttributeDataRecord, String> ATTRIBUTE_FORMAT = createField("attribute_format", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>thehomeland.attribute_data.rule_id</code>.
	 */
	public final TableField<AttributeDataRecord, Integer> RULE_ID = createField("rule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>thehomeland.attribute_data</code> table reference
	 */
	public AttributeData() {
		this("attribute_data", null);
	}

	/**
	 * Create an aliased <code>thehomeland.attribute_data</code> table reference
	 */
	public AttributeData(String alias) {
		this(alias, ATTRIBUTE_DATA);
	}

	private AttributeData(String alias, Table<AttributeDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private AttributeData(String alias, Table<AttributeDataRecord> aliased, Field<?>[] parameters) {
		super(alias, Thehomeland.THEHOMELAND, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AttributeDataRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AttributeDataRecord, ?>>asList(Keys.ATTRIBUTE_DATA_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttributeData as(String alias) {
		return new AttributeData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AttributeData rename(String name) {
		return new AttributeData(name, null);
	}
}
