/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.nazymko.th.parser.autodao.Keys;
import org.nazymko.th.parser.autodao.Thehomeland;
import org.nazymko.th.parser.autodao.tables.records.ThAttributeDataRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThAttributeData extends TableImpl<ThAttributeDataRecord> {

	/**
	 * The reference instance of <code>thehomeland.th_attribute_data</code>
	 */
	public static final ThAttributeData TH_ATTRIBUTE_DATA = new ThAttributeData();
	private static final long serialVersionUID = -411048139;
	/**
	 * The column <code>thehomeland.th_attribute_data.id</code>.
	 */
	public final TableField<ThAttributeDataRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.site_id</code>.
	 */
	public final TableField<ThAttributeDataRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.page_id</code>.
	 */
	public final TableField<ThAttributeDataRecord, Integer> PAGE_ID = createField("page_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.attribute_name</code>.
	 */
	public final TableField<ThAttributeDataRecord, String> ATTRIBUTE_NAME = createField("attribute_name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.attribute_value</code>.
	 */
	public final TableField<ThAttributeDataRecord, String> ATTRIBUTE_VALUE = createField("attribute_value", org.jooq.impl.SQLDataType.CLOB, this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.attribute_index</code>.
	 */
	public final TableField<ThAttributeDataRecord, Integer> ATTRIBUTE_INDEX = createField("attribute_index", org.jooq.impl.SQLDataType.INTEGER, this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.attribute_type</code>.
	 */
	public final TableField<ThAttributeDataRecord, String> ATTRIBUTE_TYPE = createField("attribute_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.attribute_format</code>.
	 */
	public final TableField<ThAttributeDataRecord, String> ATTRIBUTE_FORMAT = createField("attribute_format", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");
	/**
	 * The column <code>thehomeland.th_attribute_data.rule_id</code>.
	 */
	public final TableField<ThAttributeDataRecord, Integer> RULE_ID = createField("rule_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>thehomeland.th_attribute_data</code> table reference
	 */
	public ThAttributeData() {
		this("th_attribute_data", null);
	}

	/**
	 * Create an aliased <code>thehomeland.th_attribute_data</code> table reference
	 */
	public ThAttributeData(String alias) {
		this(alias, TH_ATTRIBUTE_DATA);
	}

	private ThAttributeData(String alias, Table<ThAttributeDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private ThAttributeData(String alias, Table<ThAttributeDataRecord> aliased, Field<?>[] parameters) {
		super(alias, Thehomeland.THEHOMELAND, aliased, parameters, "");
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ThAttributeDataRecord> getRecordType() {
		return ThAttributeDataRecord.class;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ThAttributeDataRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TH_ATTRIBUTE_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ThAttributeDataRecord> getPrimaryKey() {
		return Keys.KEY_TH_ATTRIBUTE_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ThAttributeDataRecord>> getKeys() {
		return Arrays.<UniqueKey<ThAttributeDataRecord>>asList(Keys.KEY_TH_ATTRIBUTE_DATA_PRIMARY, Keys.KEY_TH_ATTRIBUTE_DATA_UNIQUE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ThAttributeDataRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ThAttributeDataRecord, ?>>asList(Keys.TH_ATTRIBUTE_DATA_IBFK_2, Keys.TH_ATTRIBUTE_DATA_IBFK_3, Keys.TH_ATTRIBUTE_DATA_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThAttributeData as(String alias) {
		return new ThAttributeData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ThAttributeData rename(String name) {
		return new ThAttributeData(name, null);
	}
}
