/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.th.parser.autodao.Keys;
import org.nazymko.th.parser.autodao.Thehomeland;
import org.nazymko.th.parser.autodao.tables.records.ThPageRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThPage extends TableImpl<ThPageRecord> {

	private static final long serialVersionUID = 1051491196;

	/**
	 * The reference instance of <code>thehomeland.th_page</code>
	 */
	public static final ThPage TH_PAGE = new ThPage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ThPageRecord> getRecordType() {
		return ThPageRecord.class;
	}

	/**
	 * The column <code>thehomeland.th_page.id</code>.
	 */
	public final TableField<ThPageRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>thehomeland.th_page.page_url</code>.
	 */
	public final TableField<ThPageRecord, String> PAGE_URL = createField("page_url", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>thehomeland.th_page.version</code>.
	 */
	public final TableField<ThPageRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>thehomeland.th_page.authority</code>.
	 */
	public final TableField<ThPageRecord, String> AUTHORITY = createField("authority", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>thehomeland.th_page.site_id</code>.
	 */
	public final TableField<ThPageRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>thehomeland.th_page.visited_at</code>.
	 */
	public final TableField<ThPageRecord, Timestamp> VISITED_AT = createField("visited_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>thehomeland.th_page.type</code>.
	 */
	public final TableField<ThPageRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>thehomeland.th_page.registered_at</code>.
	 */
	public final TableField<ThPageRecord, Timestamp> REGISTERED_AT = createField("registered_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>thehomeland.th_page.sourcePage</code>.
	 */
	public final TableField<ThPageRecord, Integer> SOURCEPAGE = createField("sourcePage", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>thehomeland.th_page.task_run_id</code>.
	 */
	public final TableField<ThPageRecord, Integer> TASK_RUN_ID = createField("task_run_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>thehomeland.th_page</code> table reference
	 */
	public ThPage() {
		this("th_page", null);
	}

	/**
	 * Create an aliased <code>thehomeland.th_page</code> table reference
	 */
	public ThPage(String alias) {
		this(alias, TH_PAGE);
	}

	private ThPage(String alias, Table<ThPageRecord> aliased) {
		this(alias, aliased, null);
	}

	private ThPage(String alias, Table<ThPageRecord> aliased, Field<?>[] parameters) {
		super(alias, Thehomeland.THEHOMELAND, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ThPageRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TH_PAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ThPageRecord> getPrimaryKey() {
		return Keys.KEY_TH_PAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ThPageRecord>> getKeys() {
		return Arrays.<UniqueKey<ThPageRecord>>asList(Keys.KEY_TH_PAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ThPageRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ThPageRecord, ?>>asList(Keys.TH_PAGE_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThPage as(String alias) {
		return new ThPage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ThPage rename(String name) {
		return new ThPage(name, null);
	}
}
