/**
 * This class is generated by jOOQ
 */
package org.nazymko.th.parser.autodao.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.th.parser.autodao.Keys;
import org.nazymko.th.parser.autodao.Thehomeland;
import org.nazymko.th.parser.autodao.tables.records.TTaskRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTask extends TableImpl<TTaskRecord> {

	private static final long serialVersionUID = -331659275;

	/**
	 * The reference instance of <code>thehomeland.t_task</code>
	 */
	public static final TTask T_TASK = new TTask();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TTaskRecord> getRecordType() {
		return TTaskRecord.class;
	}

	/**
	 * The column <code>thehomeland.t_task.id</code>.
	 */
	public final TableField<TTaskRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>thehomeland.t_task.start_at</code>.
	 */
	public final TableField<TTaskRecord, Timestamp> START_AT = createField("start_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>thehomeland.t_task.schedule_source_id</code>.
	 */
	public final TableField<TTaskRecord, Integer> SCHEDULE_SOURCE_ID = createField("schedule_source_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>thehomeland.t_task.status</code>.
	 */
	public final TableField<TTaskRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>thehomeland.t_task.message</code>.
	 */
	public final TableField<TTaskRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>thehomeland.t_task.is_enabled</code>.
	 */
	public final TableField<TTaskRecord, Boolean> IS_ENABLED = createField("is_enabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>thehomeland.t_task.finish_at</code>.
	 */
	public final TableField<TTaskRecord, Timestamp> FINISH_AT = createField("finish_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>thehomeland.t_task</code> table reference
	 */
	public TTask() {
		this("t_task", null);
	}

	/**
	 * Create an aliased <code>thehomeland.t_task</code> table reference
	 */
	public TTask(String alias) {
		this(alias, T_TASK);
	}

	private TTask(String alias, Table<TTaskRecord> aliased) {
		this(alias, aliased, null);
	}

	private TTask(String alias, Table<TTaskRecord> aliased, Field<?>[] parameters) {
		super(alias, Thehomeland.THEHOMELAND, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TTaskRecord, Integer> getIdentity() {
		return Keys.IDENTITY_T_TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TTaskRecord> getPrimaryKey() {
		return Keys.KEY_T_TASK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TTaskRecord>> getKeys() {
		return Arrays.<UniqueKey<TTaskRecord>>asList(Keys.KEY_T_TASK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TTaskRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TTaskRecord, ?>>asList(Keys.T_TASK_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TTask as(String alias) {
		return new TTask(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TTask rename(String name) {
		return new TTask(name, null);
	}
}
